-- ============================================================
-- PathBinder — Discord bot tables
-- Run in: Supabase Dashboard → SQL Editor → New query
--
-- Three tables for the custom Discord bot at /api/discord-bot.js:
--   • discord_links       — permanent Discord-user → PathBinder-user link
--   • discord_link_codes  — short-lived (10 min) verification codes
--   • bug_reports         — user-submitted issues from the /bug command
--
-- All idempotent. Re-running is a no-op.
-- ============================================================


-- ─── discord_links ─────────────────────────────────────────
-- One row per linked Discord account. discord_user_id is Discord's
-- snowflake (text — they're 18-19 digit ints that exceed bigint range
-- on some platforms). One PathBinder user can only have one linked
-- Discord identity; both columns are unique. The bot reads this table
-- on every `/price`, `/bug`, `/tier` invocation to resolve the caller
-- to their PathBinder profile + check subscription tier for role sync.
create table if not exists public.discord_links (
  id                uuid primary key default gen_random_uuid(),
  user_id           uuid not null references public.profiles(id) on delete cascade,
  discord_user_id   text not null,
  discord_username  text,
  linked_at         timestamptz not null default now(),
  unique (user_id),
  unique (discord_user_id)
);

-- Index for the bot's "who is this Discord user?" lookup path.
create index if not exists discord_links_discord_user_idx
  on public.discord_links (discord_user_id);


-- ─── discord_link_codes ────────────────────────────────────
-- Short-lived code generated by `/link`. User runs `/link` in
-- Discord → bot DMs them a 6-character code → user pastes it on the
-- PathBinder Account page → server confirms + writes to discord_links.
-- Codes auto-expire after 10 minutes (enforced by the API code reading
-- expires_at).
--
-- code is uppercase A-Z + 2-9 (no 0/O/1/I to avoid font confusion),
-- generated by the bot — we don't need DB uniqueness across all-time,
-- just the small live window. Unique index on (code) so a collision
-- forces regeneration.
create table if not exists public.discord_link_codes (
  code              text primary key,
  discord_user_id   text not null,
  discord_username  text,
  expires_at        timestamptz not null,
  created_at        timestamptz not null default now()
);

create index if not exists discord_link_codes_expires_idx
  on public.discord_link_codes (expires_at);


-- ─── bug_reports ───────────────────────────────────────────
-- /bug command writes here. user_id is nullable so unlinked Discord
-- users can still report bugs (just less context). status defaults to
-- 'new' so they land in a triage queue.
create table if not exists public.bug_reports (
  id                uuid primary key default gen_random_uuid(),
  user_id           uuid references public.profiles(id) on delete set null,
  discord_user_id   text,
  discord_username  text,
  channel_name      text,           -- which Discord channel they reported from
  description       text not null,
  page              text,           -- optional: page they were on (if user provides)
  status            text not null default 'new',
                    -- 'new' | 'triaging' | 'fixed' | 'wontfix' | 'duplicate'
  triage_notes      text,           -- internal admin notes
  created_at        timestamptz not null default now(),
  updated_at        timestamptz not null default now()
);

create index if not exists bug_reports_status_idx
  on public.bug_reports (status, created_at desc);
create index if not exists bug_reports_user_idx
  on public.bug_reports (user_id, created_at desc);


-- ─── RLS ────────────────────────────────────────────────────
-- All three tables are admin-and-bot-only — bot uses the service key
-- which bypasses RLS, admin UI runs through the same. End users
-- shouldn't read or write directly.
alter table public.discord_links      enable row level security;
alter table public.discord_link_codes enable row level security;
alter table public.bug_reports        enable row level security;

-- Users CAN read their own discord_link row so the Account page can
-- display "Linked as @username" status.
drop policy if exists discord_links_own_select on public.discord_links;
create policy discord_links_own_select on public.discord_links
  for select using (auth.uid() = user_id);

-- Users CAN read their own bug reports (handy if we ever surface a
-- "your reports" page in the Account section).
drop policy if exists bug_reports_own_select on public.bug_reports;
create policy bug_reports_own_select on public.bug_reports
  for select using (auth.uid() = user_id);

-- discord_link_codes stays service-key-only — no end-user access. The
-- code is a secret during its 10-minute lifetime.


-- ─── Cleanup helper ─────────────────────────────────────────
-- Optional helper to delete expired codes. The bot calls it on every
-- /link invocation so the table stays tiny without needing pg_cron.
create or replace function public.cleanup_expired_discord_codes()
returns void
language sql
security definer
as $$
  delete from public.discord_link_codes where expires_at < now();
$$;


-- ─── Confirm-link RPC ───────────────────────────────────────
-- Called from the Account page when the user pastes the code DM'd to
-- them by the bot. Runs as SECURITY DEFINER so it can write to
-- discord_links + discord_link_codes despite the locked-down RLS, but
-- only acts on behalf of the auth.uid() of the caller — there's no
-- way to use this to claim another user's Discord identity.
--
-- Returns the discord_username on success, NULL on miss/expired.
create or replace function public.confirm_discord_link(p_code text)
returns table (discord_user_id text, discord_username text)
language plpgsql
security definer
as $$
declare
  v_uid uuid := auth.uid();
  v_code record;
begin
  if v_uid is null then
    raise exception 'Not authenticated';
  end if;

  -- Normalize: strip whitespace, uppercase. Codes are case-insensitive
  -- in practice but our codes are uppercase so we normalize on read.
  p_code := upper(regexp_replace(coalesce(p_code, ''), '\s', '', 'g'));
  if length(p_code) < 6 then
    return; -- empty result
  end if;

  select * into v_code
    from public.discord_link_codes
   where upper(code) = p_code and expires_at > now()
   limit 1;
  if not found then
    return;
  end if;

  -- Upsert into discord_links (one row per user, one row per Discord id).
  insert into public.discord_links (user_id, discord_user_id, discord_username)
    values (v_uid, v_code.discord_user_id, v_code.discord_username)
    on conflict (user_id) do update
       set discord_user_id  = excluded.discord_user_id,
           discord_username = excluded.discord_username,
           linked_at        = now();

  -- Burn the code so it can't be reused.
  delete from public.discord_link_codes where code = v_code.code;

  discord_user_id  := v_code.discord_user_id;
  discord_username := v_code.discord_username;
  return next;
end
$$;

-- Allow authenticated users (only) to call the confirm RPC. anon users
-- can't link — they'd have nothing to link to.
revoke all on function public.confirm_discord_link(text) from public;
grant  execute on function public.confirm_discord_link(text) to authenticated;
