-- migration_add_op16.sql
-- ONE PIECE OP16 "The Time of Battle" -> public.catalog  (155 rows: 149 OP16 + 6 SP alt-art reprints)
-- Convention: game_type='onepiece'; id = op-<cardnumber lowercased>; card_number = full official code
--   (alt-art parallels keep the _pN suffix from the official cardlist).
-- Images: image_url points at the card-images Supabase Storage bucket. Run upload_op16_images.py to
--   populate the actual files (op/op16/<code>.webp). Order does not matter; both are idempotent.
--
-- NOTE on the 6 SP reprints below: these alt-art cards ship inside the OP16 product but their card_number
--   belongs to an earlier set (EB04/OP10/OP11/OP14/ST15). They are tagged set_code=OP16 as the distribution
--   set so they appear in the OP16 list; their real code is preserved in id + card_number. Recategorize if
--   you prefer them grouped under their origin set:
--     op-eb04-054_p1   (EB04-054_p1, Bartholomew Kuma)
--     op-op10-045_p2   (OP10-045_p2, Cavendish)
--     op-op11-067_p3   (OP11-067_p3, Charlotte Katakuri)
--     op-op14-029_p1   (OP14-029_p1, Tashigi)
--     op-op14-084_p2   (OP14-084_p2, Ms. All Sunday)
--     op-st15-005_p5   (ST15-005_p5, Portgas.D.Ace)

INSERT INTO public.catalog (
  id, name, set_name, set_code, card_number, rarity, image_url, game_type, product_type
) VALUES
  ('op-eb04-054_p1', 'Bartholomew Kuma', 'The Time of Battle', 'OP16', 'EB04-054_p1', 'SP', 'https://xjamytrhxeaynywcwfun.supabase.co/storage/v1/object/public/card-images/op/op16/EB04-054_p1.webp', 'onepiece', 'single'),
  ('op-op10-045_p2', 'Cavendish', 'The Time of Battle', 'OP16', 'OP10-045_p2', 'SP', 'https://xjamytrhxeaynywcwfun.supabase.co/storage/v1/object/public/card-images/op/op16/OP10-045_p2.webp', 'onepiece', 'single'),
  ('op-op11-067_p3', 'Charlotte Katakuri', 'The Time of Battle', 'OP16', 'OP11-067_p3', 'SP', 'https://xjamytrhxeaynywcwfun.supabase.co/storage/v1/object/public/card-images/op/op16/OP11-067_p3.webp', 'onepiece', 'single'),
  ('op-op14-029_p1', 'Tashigi', 'The Time of Battle', 'OP16', 'OP14-029_p1', 'SP', 'https://xjamytrhxeaynywcwfun.supabase.co/storage/v1/object/public/card-images/op/op16/OP14-029_p1.webp', 'onepiece', 'single'),
  ('op-op14-084_p2', 'Ms. All Sunday', 'The Time of Battle', 'OP16', 'OP14-084_p2', 'SP', 'https://xjamytrhxeaynywcwfun.supabase.co/storage/v1/object/public/card-images/op/op16/OP14-084_p2.webp', 'onepiece', 'single'),
  ('op-op16-001', 'Portgas.D.Ace', 'The Time of Battle', 'OP16', 'OP16-001', 'L', 'https://xjamytrhxeaynywcwfun.supabase.co/storage/v1/object/public/card-images/op/op16/OP16-001.webp', 'onepiece', 'single'),
  ('op-op16-001_p1', 'Portgas.D.Ace', 'The Time of Battle', 'OP16', 'OP16-001_p1', 'L', 'https://xjamytrhxeaynywcwfun.supabase.co/storage/v1/object/public/card-images/op/op16/OP16-001_p1.webp', 'onepiece', 'single'),
  ('op-op16-002', 'Izo', 'The Time of Battle', 'OP16', 'OP16-002', 'UC', 'https://xjamytrhxeaynywcwfun.supabase.co/storage/v1/object/public/card-images/op/op16/OP16-002.webp', 'onepiece', 'single'),
  ('op-op16-003', 'Edward.Newgate', 'The Time of Battle', 'OP16', 'OP16-003', 'SR', 'https://xjamytrhxeaynywcwfun.supabase.co/storage/v1/object/public/card-images/op/op16/OP16-003.webp', 'onepiece', 'single'),
  ('op-op16-003_p1', 'Edward.Newgate', 'The Time of Battle', 'OP16', 'OP16-003_p1', 'SR', 'https://xjamytrhxeaynywcwfun.supabase.co/storage/v1/object/public/card-images/op/op16/OP16-003_p1.webp', 'onepiece', 'single'),
  ('op-op16-004', 'Curiel', 'The Time of Battle', 'OP16', 'OP16-004', 'C', 'https://xjamytrhxeaynywcwfun.supabase.co/storage/v1/object/public/card-images/op/op16/OP16-004.webp', 'onepiece', 'single'),
  ('op-op16-005', 'Thatch', 'The Time of Battle', 'OP16', 'OP16-005', 'UC', 'https://xjamytrhxeaynywcwfun.supabase.co/storage/v1/object/public/card-images/op/op16/OP16-005.webp', 'onepiece', 'single'),
  ('op-op16-006', 'Shanks', 'The Time of Battle', 'OP16', 'OP16-006', 'C', 'https://xjamytrhxeaynywcwfun.supabase.co/storage/v1/object/public/card-images/op/op16/OP16-006.webp', 'onepiece', 'single'),
  ('op-op16-007', 'Jozu', 'The Time of Battle', 'OP16', 'OP16-007', 'UC', 'https://xjamytrhxeaynywcwfun.supabase.co/storage/v1/object/public/card-images/op/op16/OP16-007.webp', 'onepiece', 'single'),
  ('op-op16-008', 'Squard', 'The Time of Battle', 'OP16', 'OP16-008', 'C', 'https://xjamytrhxeaynywcwfun.supabase.co/storage/v1/object/public/card-images/op/op16/OP16-008.webp', 'onepiece', 'single'),
  ('op-op16-009', 'Speed Jil', 'The Time of Battle', 'OP16', 'OP16-009', 'C', 'https://xjamytrhxeaynywcwfun.supabase.co/storage/v1/object/public/card-images/op/op16/OP16-009.webp', 'onepiece', 'single'),
  ('op-op16-010', 'Namule', 'The Time of Battle', 'OP16', 'OP16-010', 'UC', 'https://xjamytrhxeaynywcwfun.supabase.co/storage/v1/object/public/card-images/op/op16/OP16-010.webp', 'onepiece', 'single'),
  ('op-op16-011', 'Vista', 'The Time of Battle', 'OP16', 'OP16-011', 'R', 'https://xjamytrhxeaynywcwfun.supabase.co/storage/v1/object/public/card-images/op/op16/OP16-011.webp', 'onepiece', 'single'),
  ('op-op16-011_p1', 'Vista', 'The Time of Battle', 'OP16', 'OP16-011_p1', 'TR', 'https://xjamytrhxeaynywcwfun.supabase.co/storage/v1/object/public/card-images/op/op16/OP16-011_p1.webp', 'onepiece', 'single'),
  ('op-op16-012', 'Benn.Beckman', 'The Time of Battle', 'OP16', 'OP16-012', 'R', 'https://xjamytrhxeaynywcwfun.supabase.co/storage/v1/object/public/card-images/op/op16/OP16-012.webp', 'onepiece', 'single'),
  ('op-op16-013', 'McGuy', 'The Time of Battle', 'OP16', 'OP16-013', 'C', 'https://xjamytrhxeaynywcwfun.supabase.co/storage/v1/object/public/card-images/op/op16/OP16-013.webp', 'onepiece', 'single'),
  ('op-op16-014', 'Marco', 'The Time of Battle', 'OP16', 'OP16-014', 'R', 'https://xjamytrhxeaynywcwfun.supabase.co/storage/v1/object/public/card-images/op/op16/OP16-014.webp', 'onepiece', 'single'),
  ('op-op16-014_p1', 'Marco', 'The Time of Battle', 'OP16', 'OP16-014_p1', 'R', 'https://xjamytrhxeaynywcwfun.supabase.co/storage/v1/object/public/card-images/op/op16/OP16-014_p1.webp', 'onepiece', 'single'),
  ('op-op16-015', 'Monkey.D.Luffy', 'The Time of Battle', 'OP16', 'OP16-015', 'SR', 'https://xjamytrhxeaynywcwfun.supabase.co/storage/v1/object/public/card-images/op/op16/OP16-015.webp', 'onepiece', 'single'),
  ('op-op16-015_p1', 'Monkey.D.Luffy', 'The Time of Battle', 'OP16', 'OP16-015_p1', 'SR', 'https://xjamytrhxeaynywcwfun.supabase.co/storage/v1/object/public/card-images/op/op16/OP16-015_p1.webp', 'onepiece', 'single'),
  ('op-op16-016', 'Ramba', 'The Time of Battle', 'OP16', 'OP16-016', 'C', 'https://xjamytrhxeaynywcwfun.supabase.co/storage/v1/object/public/card-images/op/op16/OP16-016.webp', 'onepiece', 'single'),
  ('op-op16-017', 'LittleOars Jr.', 'The Time of Battle', 'OP16', 'OP16-017', 'R', 'https://xjamytrhxeaynywcwfun.supabase.co/storage/v1/object/public/card-images/op/op16/OP16-017.webp', 'onepiece', 'single'),
  ('op-op16-018', 'Rockstar', 'The Time of Battle', 'OP16', 'OP16-018', 'C', 'https://xjamytrhxeaynywcwfun.supabase.co/storage/v1/object/public/card-images/op/op16/OP16-018.webp', 'onepiece', 'single'),
  ('op-op16-019', 'Let''s Show ''Em What We''re Made Of!!', 'The Time of Battle', 'OP16', 'OP16-019', 'C', 'https://xjamytrhxeaynywcwfun.supabase.co/storage/v1/object/public/card-images/op/op16/OP16-019.webp', 'onepiece', 'single'),
  ('op-op16-020', 'If You''re Coming with Me... Kiss Your Lives Goodbye!!', 'The Time of Battle', 'OP16', 'OP16-020', 'UC', 'https://xjamytrhxeaynywcwfun.supabase.co/storage/v1/object/public/card-images/op/op16/OP16-020.webp', 'onepiece', 'single'),
  ('op-op16-021', 'Moby Dick', 'The Time of Battle', 'OP16', 'OP16-021', 'R', 'https://xjamytrhxeaynywcwfun.supabase.co/storage/v1/object/public/card-images/op/op16/OP16-021.webp', 'onepiece', 'single'),
  ('op-op16-021_p1', 'Moby Dick', 'The Time of Battle', 'OP16', 'OP16-021_p1', 'R', 'https://xjamytrhxeaynywcwfun.supabase.co/storage/v1/object/public/card-images/op/op16/OP16-021_p1.webp', 'onepiece', 'single'),
  ('op-op16-022', 'Monkey.D.Luffy', 'The Time of Battle', 'OP16', 'OP16-022', 'L', 'https://xjamytrhxeaynywcwfun.supabase.co/storage/v1/object/public/card-images/op/op16/OP16-022.webp', 'onepiece', 'single'),
  ('op-op16-022_p1', 'Monkey.D.Luffy', 'The Time of Battle', 'OP16', 'OP16-022_p1', 'L', 'https://xjamytrhxeaynywcwfun.supabase.co/storage/v1/object/public/card-images/op/op16/OP16-022_p1.webp', 'onepiece', 'single'),
  ('op-op16-023', 'Arlong', 'The Time of Battle', 'OP16', 'OP16-023', 'C', 'https://xjamytrhxeaynywcwfun.supabase.co/storage/v1/object/public/card-images/op/op16/OP16-023.webp', 'onepiece', 'single'),
  ('op-op16-024', 'Inazuma', 'The Time of Battle', 'OP16', 'OP16-024', 'UC', 'https://xjamytrhxeaynywcwfun.supabase.co/storage/v1/object/public/card-images/op/op16/OP16-024.webp', 'onepiece', 'single'),
  ('op-op16-025', 'Bunkov', 'The Time of Battle', 'OP16', 'OP16-025', 'UC', 'https://xjamytrhxeaynywcwfun.supabase.co/storage/v1/object/public/card-images/op/op16/OP16-025.webp', 'onepiece', 'single'),
  ('op-op16-026', 'Emporio.Ivankov', 'The Time of Battle', 'OP16', 'OP16-026', 'SR', 'https://xjamytrhxeaynywcwfun.supabase.co/storage/v1/object/public/card-images/op/op16/OP16-026.webp', 'onepiece', 'single'),
  ('op-op16-026_p1', 'Emporio.Ivankov', 'The Time of Battle', 'OP16', 'OP16-026_p1', 'SR', 'https://xjamytrhxeaynywcwfun.supabase.co/storage/v1/object/public/card-images/op/op16/OP16-026_p1.webp', 'onepiece', 'single'),
  ('op-op16-027', 'Jinbe', 'The Time of Battle', 'OP16', 'OP16-027', 'R', 'https://xjamytrhxeaynywcwfun.supabase.co/storage/v1/object/public/card-images/op/op16/OP16-027.webp', 'onepiece', 'single'),
  ('op-op16-028', 'Smoker', 'The Time of Battle', 'OP16', 'OP16-028', 'C', 'https://xjamytrhxeaynywcwfun.supabase.co/storage/v1/object/public/card-images/op/op16/OP16-028.webp', 'onepiece', 'single'),
  ('op-op16-029', 'Antlerkov', 'The Time of Battle', 'OP16', 'OP16-029', 'UC', 'https://xjamytrhxeaynywcwfun.supabase.co/storage/v1/object/public/card-images/op/op16/OP16-029.webp', 'onepiece', 'single'),
  ('op-op16-030', 'Trafalgar Law', 'The Time of Battle', 'OP16', 'OP16-030', 'R', 'https://xjamytrhxeaynywcwfun.supabase.co/storage/v1/object/public/card-images/op/op16/OP16-030.webp', 'onepiece', 'single'),
  ('op-op16-031', 'Buggy', 'The Time of Battle', 'OP16', 'OP16-031', 'UC', 'https://xjamytrhxeaynywcwfun.supabase.co/storage/v1/object/public/card-images/op/op16/OP16-031.webp', 'onepiece', 'single'),
  ('op-op16-032', 'Boa Hancock', 'The Time of Battle', 'OP16', 'OP16-032', 'SR', 'https://xjamytrhxeaynywcwfun.supabase.co/storage/v1/object/public/card-images/op/op16/OP16-032.webp', 'onepiece', 'single'),
  ('op-op16-032_p1', 'Boa Hancock', 'The Time of Battle', 'OP16', 'OP16-032_p1', 'SR', 'https://xjamytrhxeaynywcwfun.supabase.co/storage/v1/object/public/card-images/op/op16/OP16-032_p1.webp', 'onepiece', 'single'),
  ('op-op16-033', 'Morley', 'The Time of Battle', 'OP16', 'OP16-033', 'C', 'https://xjamytrhxeaynywcwfun.supabase.co/storage/v1/object/public/card-images/op/op16/OP16-033.webp', 'onepiece', 'single'),
  ('op-op16-034', 'Monkey.D.Luffy', 'The Time of Battle', 'OP16', 'OP16-034', 'R', 'https://xjamytrhxeaynywcwfun.supabase.co/storage/v1/object/public/card-images/op/op16/OP16-034.webp', 'onepiece', 'single'),
  ('op-op16-034_p1', 'Monkey.D.Luffy', 'The Time of Battle', 'OP16', 'OP16-034_p1', 'R', 'https://xjamytrhxeaynywcwfun.supabase.co/storage/v1/object/public/card-images/op/op16/OP16-034_p1.webp', 'onepiece', 'single'),
  ('op-op16-035', 'Roronoa Zoro', 'The Time of Battle', 'OP16', 'OP16-035', 'C', 'https://xjamytrhxeaynywcwfun.supabase.co/storage/v1/object/public/card-images/op/op16/OP16-035.webp', 'onepiece', 'single'),
  ('op-op16-036', 'Mr.2.Bon.Kurei(Bentham)', 'The Time of Battle', 'OP16', 'OP16-036', 'C', 'https://xjamytrhxeaynywcwfun.supabase.co/storage/v1/object/public/card-images/op/op16/OP16-036.webp', 'onepiece', 'single'),
  ('op-op16-037', 'Mr.3(Galdino)', 'The Time of Battle', 'OP16', 'OP16-037', 'C', 'https://xjamytrhxeaynywcwfun.supabase.co/storage/v1/object/public/card-images/op/op16/OP16-037.webp', 'onepiece', 'single'),
  ('op-op16-038', 'Let''s Go!! To the Navy Headquarters!!', 'The Time of Battle', 'OP16', 'OP16-038', 'R', 'https://xjamytrhxeaynywcwfun.supabase.co/storage/v1/object/public/card-images/op/op16/OP16-038.webp', 'onepiece', 'single'),
  ('op-op16-039', 'Gum-Gum Twin Jet Pistol', 'The Time of Battle', 'OP16', 'OP16-039', 'C', 'https://xjamytrhxeaynywcwfun.supabase.co/storage/v1/object/public/card-images/op/op16/OP16-039.webp', 'onepiece', 'single'),
  ('op-op16-040', 'Gum-Gum Hammer Rifle', 'The Time of Battle', 'OP16', 'OP16-040', 'UC', 'https://xjamytrhxeaynywcwfun.supabase.co/storage/v1/object/public/card-images/op/op16/OP16-040.webp', 'onepiece', 'single'),
  ('op-op16-041', 'Buggy', 'The Time of Battle', 'OP16', 'OP16-041', 'L', 'https://xjamytrhxeaynywcwfun.supabase.co/storage/v1/object/public/card-images/op/op16/OP16-041.webp', 'onepiece', 'single'),
  ('op-op16-041_p1', 'Buggy', 'The Time of Battle', 'OP16', 'OP16-041_p1', 'L', 'https://xjamytrhxeaynywcwfun.supabase.co/storage/v1/object/public/card-images/op/op16/OP16-041_p1.webp', 'onepiece', 'single'),
  ('op-op16-042', 'Prisoner of Impel Down', 'The Time of Battle', 'OP16', 'OP16-042', 'R', 'https://xjamytrhxeaynywcwfun.supabase.co/storage/v1/object/public/card-images/op/op16/OP16-042.webp', 'onepiece', 'single'),
  ('op-op16-043', 'Usopp', 'The Time of Battle', 'OP16', 'OP16-043', 'UC', 'https://xjamytrhxeaynywcwfun.supabase.co/storage/v1/object/public/card-images/op/op16/OP16-043.webp', 'onepiece', 'single'),
  ('op-op16-044', 'Emporio.Ivankov', 'The Time of Battle', 'OP16', 'OP16-044', 'C', 'https://xjamytrhxeaynywcwfun.supabase.co/storage/v1/object/public/card-images/op/op16/OP16-044.webp', 'onepiece', 'single'),
  ('op-op16-045', 'Crocodile', 'The Time of Battle', 'OP16', 'OP16-045', 'UC', 'https://xjamytrhxeaynywcwfun.supabase.co/storage/v1/object/public/card-images/op/op16/OP16-045.webp', 'onepiece', 'single'),
  ('op-op16-046', 'Jinbe', 'The Time of Battle', 'OP16', 'OP16-046', 'C', 'https://xjamytrhxeaynywcwfun.supabase.co/storage/v1/object/public/card-images/op/op16/OP16-046.webp', 'onepiece', 'single'),
  ('op-op16-047', 'Donquixote Doflamingo', 'The Time of Battle', 'OP16', 'OP16-047', 'C', 'https://xjamytrhxeaynywcwfun.supabase.co/storage/v1/object/public/card-images/op/op16/OP16-047.webp', 'onepiece', 'single'),
  ('op-op16-048', 'Buggy', 'The Time of Battle', 'OP16', 'OP16-048', 'SR', 'https://xjamytrhxeaynywcwfun.supabase.co/storage/v1/object/public/card-images/op/op16/OP16-048.webp', 'onepiece', 'single'),
  ('op-op16-048_p1', 'Buggy', 'The Time of Battle', 'OP16', 'OP16-048_p1', 'SR', 'https://xjamytrhxeaynywcwfun.supabase.co/storage/v1/object/public/card-images/op/op16/OP16-048_p1.webp', 'onepiece', 'single'),
  ('op-op16-049', 'Portgas.D.Ace', 'The Time of Battle', 'OP16', 'OP16-049', 'C', 'https://xjamytrhxeaynywcwfun.supabase.co/storage/v1/object/public/card-images/op/op16/OP16-049.webp', 'onepiece', 'single'),
  ('op-op16-050', 'Miss Olive', 'The Time of Battle', 'OP16', 'OP16-050', 'UC', 'https://xjamytrhxeaynywcwfun.supabase.co/storage/v1/object/public/card-images/op/op16/OP16-050.webp', 'onepiece', 'single'),
  ('op-op16-051', 'Mohji & Cabaji', 'The Time of Battle', 'OP16', 'OP16-051', 'C', 'https://xjamytrhxeaynywcwfun.supabase.co/storage/v1/object/public/card-images/op/op16/OP16-051.webp', 'onepiece', 'single'),
  ('op-op16-052', 'Monkey.D.Luffy', 'The Time of Battle', 'OP16', 'OP16-052', 'UC', 'https://xjamytrhxeaynywcwfun.supabase.co/storage/v1/object/public/card-images/op/op16/OP16-052.webp', 'onepiece', 'single'),
  ('op-op16-053', 'Roronoa Zoro', 'The Time of Battle', 'OP16', 'OP16-053', 'C', 'https://xjamytrhxeaynywcwfun.supabase.co/storage/v1/object/public/card-images/op/op16/OP16-053.webp', 'onepiece', 'single'),
  ('op-op16-054', 'Mr.1(Daz.Bonez)', 'The Time of Battle', 'OP16', 'OP16-054', 'R', 'https://xjamytrhxeaynywcwfun.supabase.co/storage/v1/object/public/card-images/op/op16/OP16-054.webp', 'onepiece', 'single'),
  ('op-op16-055', 'Mr.2.Bon.Kurei(Bentham)', 'The Time of Battle', 'OP16', 'OP16-055', 'R', 'https://xjamytrhxeaynywcwfun.supabase.co/storage/v1/object/public/card-images/op/op16/OP16-055.webp', 'onepiece', 'single'),
  ('op-op16-055_p1', 'Mr.2.Bon.Kurei(Bentham)', 'The Time of Battle', 'OP16', 'OP16-055_p1', 'R', 'https://xjamytrhxeaynywcwfun.supabase.co/storage/v1/object/public/card-images/op/op16/OP16-055_p1.webp', 'onepiece', 'single'),
  ('op-op16-056', 'Mr.3(Galdino)', 'The Time of Battle', 'OP16', 'OP16-056', 'SR', 'https://xjamytrhxeaynywcwfun.supabase.co/storage/v1/object/public/card-images/op/op16/OP16-056.webp', 'onepiece', 'single'),
  ('op-op16-056_p1', 'Mr.3(Galdino)', 'The Time of Battle', 'OP16', 'OP16-056_p1', 'SR', 'https://xjamytrhxeaynywcwfun.supabase.co/storage/v1/object/public/card-images/op/op16/OP16-056_p1.webp', 'onepiece', 'single'),
  ('op-op16-057', 'Captain Buggy''s Our Savior!!', 'The Time of Battle', 'OP16', 'OP16-057', 'C', 'https://xjamytrhxeaynywcwfun.supabase.co/storage/v1/object/public/card-images/op/op16/OP16-057.webp', 'onepiece', 'single'),
  ('op-op16-058', 'The Prisoners Are Rioting!!', 'The Time of Battle', 'OP16', 'OP16-058', 'R', 'https://xjamytrhxeaynywcwfun.supabase.co/storage/v1/object/public/card-images/op/op16/OP16-058.webp', 'onepiece', 'single'),
  ('op-op16-059', 'We''ll Change This Mission from Sneaky to Flashy!', 'The Time of Battle', 'OP16', 'OP16-059', 'UC', 'https://xjamytrhxeaynywcwfun.supabase.co/storage/v1/object/public/card-images/op/op16/OP16-059.webp', 'onepiece', 'single'),
  ('op-op16-060', 'Sengoku', 'The Time of Battle', 'OP16', 'OP16-060', 'L', 'https://xjamytrhxeaynywcwfun.supabase.co/storage/v1/object/public/card-images/op/op16/OP16-060.webp', 'onepiece', 'single'),
  ('op-op16-060_p1', 'Sengoku', 'The Time of Battle', 'OP16', 'OP16-060_p1', 'L', 'https://xjamytrhxeaynywcwfun.supabase.co/storage/v1/object/public/card-images/op/op16/OP16-060_p1.webp', 'onepiece', 'single'),
  ('op-op16-061', 'Older Brother Marine', 'The Time of Battle', 'OP16', 'OP16-061', 'C', 'https://xjamytrhxeaynywcwfun.supabase.co/storage/v1/object/public/card-images/op/op16/OP16-061.webp', 'onepiece', 'single'),
  ('op-op16-062', 'Younger Brother Marine', 'The Time of Battle', 'OP16', 'OP16-062', 'C', 'https://xjamytrhxeaynywcwfun.supabase.co/storage/v1/object/public/card-images/op/op16/OP16-062.webp', 'onepiece', 'single'),
  ('op-op16-063', 'Kuzan', 'The Time of Battle', 'OP16', 'OP16-063', 'R', 'https://xjamytrhxeaynywcwfun.supabase.co/storage/v1/object/public/card-images/op/op16/OP16-063.webp', 'onepiece', 'single'),
  ('op-op16-063_p1', 'Kuzan', 'The Time of Battle', 'OP16', 'OP16-063_p1', 'R', 'https://xjamytrhxeaynywcwfun.supabase.co/storage/v1/object/public/card-images/op/op16/OP16-063_p1.webp', 'onepiece', 'single'),
  ('op-op16-063_p2', 'Kuzan', 'The Time of Battle', 'OP16', 'OP16-063_p2', 'R', 'https://xjamytrhxeaynywcwfun.supabase.co/storage/v1/object/public/card-images/op/op16/OP16-063_p2.webp', 'onepiece', 'single'),
  ('op-op16-064', 'Koby', 'The Time of Battle', 'OP16', 'OP16-064', 'R', 'https://xjamytrhxeaynywcwfun.supabase.co/storage/v1/object/public/card-images/op/op16/OP16-064.webp', 'onepiece', 'single'),
  ('op-op16-065', 'Sakazuki', 'The Time of Battle', 'OP16', 'OP16-065', 'SR', 'https://xjamytrhxeaynywcwfun.supabase.co/storage/v1/object/public/card-images/op/op16/OP16-065.webp', 'onepiece', 'single'),
  ('op-op16-065_p1', 'Sakazuki', 'The Time of Battle', 'OP16', 'OP16-065_p1', 'SR', 'https://xjamytrhxeaynywcwfun.supabase.co/storage/v1/object/public/card-images/op/op16/OP16-065_p1.webp', 'onepiece', 'single'),
  ('op-op16-065_p2', 'Sakazuki', 'The Time of Battle', 'OP16', 'OP16-065_p2', 'SR', 'https://xjamytrhxeaynywcwfun.supabase.co/storage/v1/object/public/card-images/op/op16/OP16-065_p2.webp', 'onepiece', 'single'),
  ('op-op16-066', 'Sengoku', 'The Time of Battle', 'OP16', 'OP16-066', 'UC', 'https://xjamytrhxeaynywcwfun.supabase.co/storage/v1/object/public/card-images/op/op16/OP16-066.webp', 'onepiece', 'single'),
  ('op-op16-067', 'Tsuru', 'The Time of Battle', 'OP16', 'OP16-067', 'UC', 'https://xjamytrhxeaynywcwfun.supabase.co/storage/v1/object/public/card-images/op/op16/OP16-067.webp', 'onepiece', 'single'),
  ('op-op16-068', 'Trafalgar Law', 'The Time of Battle', 'OP16', 'OP16-068', 'C', 'https://xjamytrhxeaynywcwfun.supabase.co/storage/v1/object/public/card-images/op/op16/OP16-068.webp', 'onepiece', 'single'),
  ('op-op16-069', 'Donquixote Doflamingo', 'The Time of Battle', 'OP16', 'OP16-069', 'C', 'https://xjamytrhxeaynywcwfun.supabase.co/storage/v1/object/public/card-images/op/op16/OP16-069.webp', 'onepiece', 'single'),
  ('op-op16-070', 'Donquixote Rosinante', 'The Time of Battle', 'OP16', 'OP16-070', 'UC', 'https://xjamytrhxeaynywcwfun.supabase.co/storage/v1/object/public/card-images/op/op16/OP16-070.webp', 'onepiece', 'single'),
  ('op-op16-071', 'Benevolent King of the Waves', 'The Time of Battle', 'OP16', 'OP16-071', 'C', 'https://xjamytrhxeaynywcwfun.supabase.co/storage/v1/object/public/card-images/op/op16/OP16-071.webp', 'onepiece', 'single'),
  ('op-op16-072', 'Hannyabal', 'The Time of Battle', 'OP16', 'OP16-072', 'C', 'https://xjamytrhxeaynywcwfun.supabase.co/storage/v1/object/public/card-images/op/op16/OP16-072.webp', 'onepiece', 'single'),
  ('op-op16-073', 'Borsalino', 'The Time of Battle', 'OP16', 'OP16-073', 'R', 'https://xjamytrhxeaynywcwfun.supabase.co/storage/v1/object/public/card-images/op/op16/OP16-073.webp', 'onepiece', 'single'),
  ('op-op16-073_p1', 'Borsalino', 'The Time of Battle', 'OP16', 'OP16-073_p1', 'R', 'https://xjamytrhxeaynywcwfun.supabase.co/storage/v1/object/public/card-images/op/op16/OP16-073_p1.webp', 'onepiece', 'single'),
  ('op-op16-073_p2', 'Borsalino', 'The Time of Battle', 'OP16', 'OP16-073_p2', 'R', 'https://xjamytrhxeaynywcwfun.supabase.co/storage/v1/object/public/card-images/op/op16/OP16-073_p2.webp', 'onepiece', 'single'),
  ('op-op16-074', 'Magellan', 'The Time of Battle', 'OP16', 'OP16-074', 'C', 'https://xjamytrhxeaynywcwfun.supabase.co/storage/v1/object/public/card-images/op/op16/OP16-074.webp', 'onepiece', 'single'),
  ('op-op16-075', 'Monkey.D.Garp', 'The Time of Battle', 'OP16', 'OP16-075', 'C', 'https://xjamytrhxeaynywcwfun.supabase.co/storage/v1/object/public/card-images/op/op16/OP16-075.webp', 'onepiece', 'single'),
  ('op-op16-076', 'The Three Admirals!!', 'The Time of Battle', 'OP16', 'OP16-076', 'UC', 'https://xjamytrhxeaynywcwfun.supabase.co/storage/v1/object/public/card-images/op/op16/OP16-076.webp', 'onepiece', 'single'),
  ('op-op16-077', '"Buddha" Sengoku', 'The Time of Battle', 'OP16', 'OP16-077', 'R', 'https://xjamytrhxeaynywcwfun.supabase.co/storage/v1/object/public/card-images/op/op16/OP16-077.webp', 'onepiece', 'single'),
  ('op-op16-078', 'Marineford', 'The Time of Battle', 'OP16', 'OP16-078', 'UC', 'https://xjamytrhxeaynywcwfun.supabase.co/storage/v1/object/public/card-images/op/op16/OP16-078.webp', 'onepiece', 'single'),
  ('op-op16-079', 'Yamato', 'The Time of Battle', 'OP16', 'OP16-079', 'L', 'https://xjamytrhxeaynywcwfun.supabase.co/storage/v1/object/public/card-images/op/op16/OP16-079.webp', 'onepiece', 'single'),
  ('op-op16-079_p1', 'Yamato', 'The Time of Battle', 'OP16', 'OP16-079_p1', 'L', 'https://xjamytrhxeaynywcwfun.supabase.co/storage/v1/object/public/card-images/op/op16/OP16-079_p1.webp', 'onepiece', 'single'),
  ('op-op16-080', 'Marshall.D.Teach', 'The Time of Battle', 'OP16', 'OP16-080', 'L', 'https://xjamytrhxeaynywcwfun.supabase.co/storage/v1/object/public/card-images/op/op16/OP16-080.webp', 'onepiece', 'single'),
  ('op-op16-080_p1', 'Marshall.D.Teach', 'The Time of Battle', 'OP16', 'OP16-080_p1', 'L', 'https://xjamytrhxeaynywcwfun.supabase.co/storage/v1/object/public/card-images/op/op16/OP16-080_p1.webp', 'onepiece', 'single'),
  ('op-op16-081', 'Otama', 'The Time of Battle', 'OP16', 'OP16-081', 'C', 'https://xjamytrhxeaynywcwfun.supabase.co/storage/v1/object/public/card-images/op/op16/OP16-081.webp', 'onepiece', 'single'),
  ('op-op16-082', 'Kin''emon', 'The Time of Battle', 'OP16', 'OP16-082', 'SR', 'https://xjamytrhxeaynywcwfun.supabase.co/storage/v1/object/public/card-images/op/op16/OP16-082.webp', 'onepiece', 'single'),
  ('op-op16-082_p1', 'Kin''emon', 'The Time of Battle', 'OP16', 'OP16-082_p1', 'SR', 'https://xjamytrhxeaynywcwfun.supabase.co/storage/v1/object/public/card-images/op/op16/OP16-082_p1.webp', 'onepiece', 'single'),
  ('op-op16-083', 'Kouzuki Oden', 'The Time of Battle', 'OP16', 'OP16-083', 'C', 'https://xjamytrhxeaynywcwfun.supabase.co/storage/v1/object/public/card-images/op/op16/OP16-083.webp', 'onepiece', 'single'),
  ('op-op16-084', 'Kouzuki Momonosuke', 'The Time of Battle', 'OP16', 'OP16-084', 'UC', 'https://xjamytrhxeaynywcwfun.supabase.co/storage/v1/object/public/card-images/op/op16/OP16-084.webp', 'onepiece', 'single'),
  ('op-op16-085', 'Kouzuki Momonosuke', 'The Time of Battle', 'OP16', 'OP16-085', 'R', 'https://xjamytrhxeaynywcwfun.supabase.co/storage/v1/object/public/card-images/op/op16/OP16-085.webp', 'onepiece', 'single'),
  ('op-op16-085_p1', 'Kouzuki Momonosuke', 'The Time of Battle', 'OP16', 'OP16-085_p1', 'R', 'https://xjamytrhxeaynywcwfun.supabase.co/storage/v1/object/public/card-images/op/op16/OP16-085_p1.webp', 'onepiece', 'single'),
  ('op-op16-086', 'Sanji', 'The Time of Battle', 'OP16', 'OP16-086', 'C', 'https://xjamytrhxeaynywcwfun.supabase.co/storage/v1/object/public/card-images/op/op16/OP16-086.webp', 'onepiece', 'single'),
  ('op-op16-087', 'Shinobu', 'The Time of Battle', 'OP16', 'OP16-087', 'UC', 'https://xjamytrhxeaynywcwfun.supabase.co/storage/v1/object/public/card-images/op/op16/OP16-087.webp', 'onepiece', 'single'),
  ('op-op16-088', 'Shimotsuki Ushimaru', 'The Time of Battle', 'OP16', 'OP16-088', 'C', 'https://xjamytrhxeaynywcwfun.supabase.co/storage/v1/object/public/card-images/op/op16/OP16-088.webp', 'onepiece', 'single'),
  ('op-op16-089', 'Dracule Mihawk', 'The Time of Battle', 'OP16', 'OP16-089', 'C', 'https://xjamytrhxeaynywcwfun.supabase.co/storage/v1/object/public/card-images/op/op16/OP16-089.webp', 'onepiece', 'single'),
  ('op-op16-090', 'Tony Tony.Chopper', 'The Time of Battle', 'OP16', 'OP16-090', 'C', 'https://xjamytrhxeaynywcwfun.supabase.co/storage/v1/object/public/card-images/op/op16/OP16-090.webp', 'onepiece', 'single'),
  ('op-op16-091', 'Nami', 'The Time of Battle', 'OP16', 'OP16-091', 'R', 'https://xjamytrhxeaynywcwfun.supabase.co/storage/v1/object/public/card-images/op/op16/OP16-091.webp', 'onepiece', 'single'),
  ('op-op16-092', 'Nico Robin', 'The Time of Battle', 'OP16', 'OP16-092', 'UC', 'https://xjamytrhxeaynywcwfun.supabase.co/storage/v1/object/public/card-images/op/op16/OP16-092.webp', 'onepiece', 'single'),
  ('op-op16-093', 'Bartholomew Kuma', 'The Time of Battle', 'OP16', 'OP16-093', 'C', 'https://xjamytrhxeaynywcwfun.supabase.co/storage/v1/object/public/card-images/op/op16/OP16-093.webp', 'onepiece', 'single'),
  ('op-op16-094', 'Portgas.D.Ace', 'The Time of Battle', 'OP16', 'OP16-094', 'UC', 'https://xjamytrhxeaynywcwfun.supabase.co/storage/v1/object/public/card-images/op/op16/OP16-094.webp', 'onepiece', 'single'),
  ('op-op16-095', 'Monkey.D.Luffy', 'The Time of Battle', 'OP16', 'OP16-095', 'R', 'https://xjamytrhxeaynywcwfun.supabase.co/storage/v1/object/public/card-images/op/op16/OP16-095.webp', 'onepiece', 'single'),
  ('op-op16-096', 'Yamato', 'The Time of Battle', 'OP16', 'OP16-096', 'R', 'https://xjamytrhxeaynywcwfun.supabase.co/storage/v1/object/public/card-images/op/op16/OP16-096.webp', 'onepiece', 'single'),
  ('op-op16-097', 'Yamato', 'The Time of Battle', 'OP16', 'OP16-097', 'R', 'https://xjamytrhxeaynywcwfun.supabase.co/storage/v1/object/public/card-images/op/op16/OP16-097.webp', 'onepiece', 'single'),
  ('op-op16-098', 'Yamato', 'The Time of Battle', 'OP16', 'OP16-098', 'SR', 'https://xjamytrhxeaynywcwfun.supabase.co/storage/v1/object/public/card-images/op/op16/OP16-098.webp', 'onepiece', 'single'),
  ('op-op16-098_p1', 'Yamato', 'The Time of Battle', 'OP16', 'OP16-098_p1', 'SR', 'https://xjamytrhxeaynywcwfun.supabase.co/storage/v1/object/public/card-images/op/op16/OP16-098_p1.webp', 'onepiece', 'single'),
  ('op-op16-099', 'I''ve Come Here... To Cut Those Chains!!!', 'The Time of Battle', 'OP16', 'OP16-099', 'UC', 'https://xjamytrhxeaynywcwfun.supabase.co/storage/v1/object/public/card-images/op/op16/OP16-099.webp', 'onepiece', 'single'),
  ('op-op16-100', 'Hallowed Glacier Slash', 'The Time of Battle', 'OP16', 'OP16-100', 'C', 'https://xjamytrhxeaynywcwfun.supabase.co/storage/v1/object/public/card-images/op/op16/OP16-100.webp', 'onepiece', 'single'),
  ('op-op16-101', 'Mahoroba', 'The Time of Battle', 'OP16', 'OP16-101', 'C', 'https://xjamytrhxeaynywcwfun.supabase.co/storage/v1/object/public/card-images/op/op16/OP16-101.webp', 'onepiece', 'single'),
  ('op-op16-102', 'Avalo Pizarro', 'The Time of Battle', 'OP16', 'OP16-102', 'UC', 'https://xjamytrhxeaynywcwfun.supabase.co/storage/v1/object/public/card-images/op/op16/OP16-102.webp', 'onepiece', 'single'),
  ('op-op16-103', 'Van Augur', 'The Time of Battle', 'OP16', 'OP16-103', 'UC', 'https://xjamytrhxeaynywcwfun.supabase.co/storage/v1/object/public/card-images/op/op16/OP16-103.webp', 'onepiece', 'single'),
  ('op-op16-104', 'Catarina Devon', 'The Time of Battle', 'OP16', 'OP16-104', 'R', 'https://xjamytrhxeaynywcwfun.supabase.co/storage/v1/object/public/card-images/op/op16/OP16-104.webp', 'onepiece', 'single'),
  ('op-op16-105', 'Gecko Moria', 'The Time of Battle', 'OP16', 'OP16-105', 'C', 'https://xjamytrhxeaynywcwfun.supabase.co/storage/v1/object/public/card-images/op/op16/OP16-105.webp', 'onepiece', 'single'),
  ('op-op16-106', 'Sanjuan.Wolf', 'The Time of Battle', 'OP16', 'OP16-106', 'R', 'https://xjamytrhxeaynywcwfun.supabase.co/storage/v1/object/public/card-images/op/op16/OP16-106.webp', 'onepiece', 'single'),
  ('op-op16-107', 'Jesus Burgess', 'The Time of Battle', 'OP16', 'OP16-107', 'C', 'https://xjamytrhxeaynywcwfun.supabase.co/storage/v1/object/public/card-images/op/op16/OP16-107.webp', 'onepiece', 'single'),
  ('op-op16-108', 'Shiryu', 'The Time of Battle', 'OP16', 'OP16-108', 'SR', 'https://xjamytrhxeaynywcwfun.supabase.co/storage/v1/object/public/card-images/op/op16/OP16-108.webp', 'onepiece', 'single'),
  ('op-op16-108_p1', 'Shiryu', 'The Time of Battle', 'OP16', 'OP16-108_p1', 'SR', 'https://xjamytrhxeaynywcwfun.supabase.co/storage/v1/object/public/card-images/op/op16/OP16-108_p1.webp', 'onepiece', 'single'),
  ('op-op16-109', 'Doc Q', 'The Time of Battle', 'OP16', 'OP16-109', 'UC', 'https://xjamytrhxeaynywcwfun.supabase.co/storage/v1/object/public/card-images/op/op16/OP16-109.webp', 'onepiece', 'single'),
  ('op-op16-110', 'Vasco Shot', 'The Time of Battle', 'OP16', 'OP16-110', 'R', 'https://xjamytrhxeaynywcwfun.supabase.co/storage/v1/object/public/card-images/op/op16/OP16-110.webp', 'onepiece', 'single'),
  ('op-op16-111', 'Boa Sandersonia', 'The Time of Battle', 'OP16', 'OP16-111', 'C', 'https://xjamytrhxeaynywcwfun.supabase.co/storage/v1/object/public/card-images/op/op16/OP16-111.webp', 'onepiece', 'single'),
  ('op-op16-112', 'Boa Hancock', 'The Time of Battle', 'OP16', 'OP16-112', 'C', 'https://xjamytrhxeaynywcwfun.supabase.co/storage/v1/object/public/card-images/op/op16/OP16-112.webp', 'onepiece', 'single'),
  ('op-op16-113', 'Boa Marigold', 'The Time of Battle', 'OP16', 'OP16-113', 'UC', 'https://xjamytrhxeaynywcwfun.supabase.co/storage/v1/object/public/card-images/op/op16/OP16-113.webp', 'onepiece', 'single'),
  ('op-op16-114', 'Laffitte', 'The Time of Battle', 'OP16', 'OP16-114', 'C', 'https://xjamytrhxeaynywcwfun.supabase.co/storage/v1/object/public/card-images/op/op16/OP16-114.webp', 'onepiece', 'single'),
  ('op-op16-115', 'Black Vortex', 'The Time of Battle', 'OP16', 'OP16-115', 'UC', 'https://xjamytrhxeaynywcwfun.supabase.co/storage/v1/object/public/card-images/op/op16/OP16-115.webp', 'onepiece', 'single'),
  ('op-op16-116', 'Zehahahahaha!', 'The Time of Battle', 'OP16', 'OP16-116', 'R', 'https://xjamytrhxeaynywcwfun.supabase.co/storage/v1/object/public/card-images/op/op16/OP16-116.webp', 'onepiece', 'single'),
  ('op-op16-116_p1', 'Zehahahahaha!', 'The Time of Battle', 'OP16', 'OP16-116_p1', 'R', 'https://xjamytrhxeaynywcwfun.supabase.co/storage/v1/object/public/card-images/op/op16/OP16-116_p1.webp', 'onepiece', 'single'),
  ('op-op16-117', 'Black Hole', 'The Time of Battle', 'OP16', 'OP16-117', 'C', 'https://xjamytrhxeaynywcwfun.supabase.co/storage/v1/object/public/card-images/op/op16/OP16-117.webp', 'onepiece', 'single'),
  ('op-op16-118', 'Portgas.D.Ace', 'The Time of Battle', 'OP16', 'OP16-118', 'SEC', 'https://xjamytrhxeaynywcwfun.supabase.co/storage/v1/object/public/card-images/op/op16/OP16-118.webp', 'onepiece', 'single'),
  ('op-op16-118_p1', 'Portgas.D.Ace', 'The Time of Battle', 'OP16', 'OP16-118_p1', 'SEC', 'https://xjamytrhxeaynywcwfun.supabase.co/storage/v1/object/public/card-images/op/op16/OP16-118_p1.webp', 'onepiece', 'single'),
  ('op-op16-119', 'Marshall.D.Teach', 'The Time of Battle', 'OP16', 'OP16-119', 'SEC', 'https://xjamytrhxeaynywcwfun.supabase.co/storage/v1/object/public/card-images/op/op16/OP16-119.webp', 'onepiece', 'single'),
  ('op-op16-119_p1', 'Marshall.D.Teach', 'The Time of Battle', 'OP16', 'OP16-119_p1', 'SEC', 'https://xjamytrhxeaynywcwfun.supabase.co/storage/v1/object/public/card-images/op/op16/OP16-119_p1.webp', 'onepiece', 'single'),
  ('op-st15-005_p5', 'Portgas.D.Ace', 'The Time of Battle', 'OP16', 'ST15-005_p5', 'SP', 'https://xjamytrhxeaynywcwfun.supabase.co/storage/v1/object/public/card-images/op/op16/ST15-005_p5.webp', 'onepiece', 'single')
ON CONFLICT (id) DO UPDATE SET
  name         = EXCLUDED.name,
  set_name     = EXCLUDED.set_name,
  set_code     = EXCLUDED.set_code,
  card_number  = EXCLUDED.card_number,
  rarity       = EXCLUDED.rarity,
  image_url    = COALESCE(EXCLUDED.image_url, public.catalog.image_url),
  game_type    = EXCLUDED.game_type,
  product_type = EXCLUDED.product_type;

-- Verify (expect 155):
SELECT count(*) FROM public.catalog WHERE game_type='onepiece' AND set_code='OP16';
SELECT id, name, card_number, rarity, image_url FROM public.catalog
 WHERE game_type='onepiece' AND set_code='OP16' ORDER BY id;