-- ============================================================
-- PathBinder — Subsidiary beta invites
-- Run in: Supabase Dashboard → SQL Editor → New query
--
-- Concept
-- -------
-- Beta testers in certain tiers can give a limited number of
-- invites to friends. Quotas (as of this migration):
--
--   founding   →  3 invites, granted_tier = 'vendor',     3 months
--   enthusiast →  1 invite,  granted_tier = 'enthusiast', 6 months
--   collector  →  1 invite,  granted_tier = 'collector',  6 months
--
-- (Vendor and shop beta testers don't get subsidiary invites.)
--
-- Each invite is a code the friend redeems on signup. The grant
-- temporarily promotes them to the granted tier; after the
-- duration elapses they revert to 'free' and the app shows them
-- a "this is what you'll miss" upgrade prompt.
--
-- Idempotent — re-running is safe.

-- ── Profile additions ────────────────────────────────────────
-- granted_tier_expires_at: when the subsidiary-granted tier
-- reverts to 'free'. NULL for users on a normal paid tier or
-- permanent founder access.
ALTER TABLE public.profiles
  ADD COLUMN IF NOT EXISTS granted_tier_expires_at timestamptz;

-- granted_tier_source: 'subsidiary_invite' for friends invited
-- by a beta tester. Future room for 'promo', 'referral', etc.
-- NULL for everyone who reached their tier through normal billing
-- or founder permanence.
ALTER TABLE public.profiles
  ADD COLUMN IF NOT EXISTS granted_tier_source text;

COMMENT ON COLUMN public.profiles.granted_tier_expires_at IS
  'When a subsidiary-granted tier reverts to free. NULL = permanent or paid.';
COMMENT ON COLUMN public.profiles.granted_tier_source IS
  'How the user reached their current tier (subsidiary_invite, etc.). NULL = paid / founder.';


-- ── Invites table ────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.subsidiary_invites (
  id              uuid primary key default gen_random_uuid(),
  -- Human-friendly invite code. Generated by create_subsidiary_invite()
  -- as a four-block format: ABCD-EFGH-IJKL (uppercase, alpha-numeric).
  code            text unique not null,
  -- Who generated it.
  inviter_id      uuid not null references public.profiles(id) on delete cascade,
  -- What beta tier the inviter held at issue time. Captured for
  -- audit; the quota check pulls the inviter's current tier when
  -- generating new invites, but historical rows keep their source
  -- intact even if the inviter's tier later changes.
  inviter_tier    text not null check (inviter_tier in ('founding','enthusiast','collector')),
  -- What tier the invitee receives on claim.
  granted_tier    text not null check (granted_tier in ('vendor','enthusiast','collector')),
  -- 3 or 6 currently — kept as int for future flexibility.
  duration_months int  not null check (duration_months > 0),
  -- Lifecycle timestamps. claimed_at / claimed_by / expires_at
  -- are populated when the invitee redeems. revoked_at is set
  -- if an admin or the inviter rescinds an unclaimed code.
  created_at      timestamptz not null default now(),
  claimed_at      timestamptz,
  claimed_by      uuid references public.profiles(id),
  expires_at      timestamptz,
  revoked_at      timestamptz
);

CREATE INDEX IF NOT EXISTS idx_subsidiary_invites_inviter
  ON public.subsidiary_invites (inviter_id);
CREATE INDEX IF NOT EXISTS idx_subsidiary_invites_claimed_by
  ON public.subsidiary_invites (claimed_by);
CREATE INDEX IF NOT EXISTS idx_subsidiary_invites_expiring
  ON public.subsidiary_invites (expires_at)
  WHERE claimed_at IS NOT NULL AND expires_at IS NOT NULL;


-- ── RLS ──────────────────────────────────────────────────────
ALTER TABLE public.subsidiary_invites ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "subsidiary_invites_self_select" ON public.subsidiary_invites;
CREATE POLICY "subsidiary_invites_self_select"
  ON public.subsidiary_invites
  FOR SELECT
  USING (
    -- Inviter sees their own invites; claimed user sees the row
    -- they claimed; admins see everything.
    inviter_id = auth.uid()
    OR claimed_by = auth.uid()
    OR EXISTS (SELECT 1 FROM public.profiles p
                WHERE p.id = auth.uid() AND coalesce(p.is_admin, false))
  );

-- Inserts only via SECURITY DEFINER helper below, so no direct
-- insert policy is needed.


-- ── Quota config ─────────────────────────────────────────────
-- Single source of truth for which beta tiers get how many
-- invites, what tier they grant, and for how long. Other functions
-- and the app UI both read from this.
CREATE OR REPLACE FUNCTION public.subsidiary_invite_config(p_beta_tier text)
RETURNS TABLE(invite_quota int, granted_tier text, duration_months int)
LANGUAGE sql IMMUTABLE AS $$
  SELECT CASE p_beta_tier
           WHEN 'founding'   THEN 3
           WHEN 'enthusiast' THEN 1
           WHEN 'collector'  THEN 1
           ELSE 0
         END AS invite_quota,
         CASE p_beta_tier
           WHEN 'founding'   THEN 'vendor'
           WHEN 'enthusiast' THEN 'enthusiast'
           WHEN 'collector'  THEN 'collector'
           ELSE NULL
         END AS granted_tier,
         CASE p_beta_tier
           WHEN 'founding'   THEN 3
           WHEN 'enthusiast' THEN 6
           WHEN 'collector'  THEN 6
           ELSE 0
         END AS duration_months;
$$;
GRANT EXECUTE ON FUNCTION public.subsidiary_invite_config(text) TO anon, authenticated;


-- ── Quota check ──────────────────────────────────────────────
-- Returns (used, remaining, granted_tier, duration_months) for
-- the caller. "used" counts non-revoked invites the user has
-- generated (claimed or not — once issued, the slot is gone).
-- granted_tier and duration_months come from the config table.
CREATE OR REPLACE FUNCTION public.beta_subsidiary_quota()
RETURNS TABLE(
  used int,
  remaining int,
  granted_tier text,
  duration_months int
)
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE
  v_uid uuid := auth.uid();
  v_beta_tier text;
  v_used int;
  v_quota int;
  v_granted text;
  v_dur int;
BEGIN
  IF v_uid IS NULL THEN
    RETURN QUERY SELECT 0, 0, NULL::text, 0;
    RETURN;
  END IF;
  SELECT tier INTO v_beta_tier
    FROM public.beta_testers
    WHERE user_id = v_uid AND revoked_at IS NULL
    LIMIT 1;
  IF v_beta_tier IS NULL THEN
    RETURN QUERY SELECT 0, 0, NULL::text, 0;
    RETURN;
  END IF;
  SELECT invite_quota, granted_tier, duration_months
    INTO v_quota, v_granted, v_dur
    FROM public.subsidiary_invite_config(v_beta_tier);
  IF v_quota = 0 THEN
    RETURN QUERY SELECT 0, 0, NULL::text, 0;
    RETURN;
  END IF;
  SELECT count(*)::int INTO v_used
    FROM public.subsidiary_invites
    WHERE inviter_id = v_uid AND revoked_at IS NULL;
  RETURN QUERY SELECT v_used, greatest(v_quota - v_used, 0), v_granted, v_dur;
END;
$$;
GRANT EXECUTE ON FUNCTION public.beta_subsidiary_quota() TO authenticated;


-- ── Create invite ────────────────────────────────────────────
-- Generates a fresh code and inserts the invite row. Enforces
-- the caller's beta tier quota. Returns the created row so the
-- UI can immediately render + offer to email it.
CREATE OR REPLACE FUNCTION public.create_subsidiary_invite()
RETURNS TABLE(
  id uuid,
  code text,
  granted_tier text,
  duration_months int
)
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE
  v_uid uuid := auth.uid();
  v_beta_tier text;
  v_quota int;
  v_granted text;
  v_dur int;
  v_used int;
  v_code text;
  v_id uuid;
  v_chars text := 'ABCDEFGHJKLMNPQRSTUVWXYZ23456789'; -- skip I, O, 0, 1 for legibility
  i int;
BEGIN
  IF v_uid IS NULL THEN
    RAISE EXCEPTION 'not authenticated';
  END IF;
  SELECT tier INTO v_beta_tier
    FROM public.beta_testers
    WHERE user_id = v_uid AND revoked_at IS NULL
    LIMIT 1;
  IF v_beta_tier IS NULL THEN
    RAISE EXCEPTION 'caller is not a beta tester';
  END IF;
  SELECT invite_quota, granted_tier, duration_months
    INTO v_quota, v_granted, v_dur
    FROM public.subsidiary_invite_config(v_beta_tier);
  IF v_quota = 0 OR v_granted IS NULL THEN
    RAISE EXCEPTION 'beta tier % does not include subsidiary invites', v_beta_tier;
  END IF;
  SELECT count(*)::int INTO v_used
    FROM public.subsidiary_invites
    WHERE inviter_id = v_uid AND revoked_at IS NULL;
  IF v_used >= v_quota THEN
    RAISE EXCEPTION 'quota exhausted: % of % used', v_used, v_quota;
  END IF;

  -- Generate a unique 12-char dashed code. Retry on the (vanishingly
  -- rare) collision against the unique index.
  FOR i IN 1..20 LOOP
    v_code := substr(translate(encode(gen_random_bytes(12), 'base64'), '+/=', 'XXX'), 1, 12);
    -- Reject any code containing non-allowed chars; resample if so.
    IF v_code ~ '^[A-Za-z0-9]{12}$' THEN
      v_code := upper(substr(v_code,1,4) || '-' || substr(v_code,5,4) || '-' || substr(v_code,9,4));
      EXIT;
    END IF;
  END LOOP;

  INSERT INTO public.subsidiary_invites (code, inviter_id, inviter_tier, granted_tier, duration_months)
    VALUES (v_code, v_uid, v_beta_tier, v_granted, v_dur)
    RETURNING subsidiary_invites.id, subsidiary_invites.code,
              subsidiary_invites.granted_tier, subsidiary_invites.duration_months
    INTO v_id, v_code, v_granted, v_dur;

  RETURN QUERY SELECT v_id, v_code, v_granted, v_dur;
END;
$$;
GRANT EXECUTE ON FUNCTION public.create_subsidiary_invite() TO authenticated;


-- ── Claim invite ─────────────────────────────────────────────
-- Called from the signup / claim flow with a code. Validates the
-- code is unclaimed + unrevoked, grants the granted_tier to the
-- caller, stamps profiles.granted_tier_expires_at = now() + duration,
-- and marks the invite as claimed.
CREATE OR REPLACE FUNCTION public.claim_subsidiary_invite(p_code text)
RETURNS TABLE(
  granted_tier text,
  expires_at timestamptz
)
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE
  v_uid uuid := auth.uid();
  v_invite public.subsidiary_invites%ROWTYPE;
  v_expires timestamptz;
BEGIN
  IF v_uid IS NULL THEN
    RAISE EXCEPTION 'not authenticated';
  END IF;
  IF p_code IS NULL OR length(trim(p_code)) = 0 THEN
    RAISE EXCEPTION 'invite code required';
  END IF;

  SELECT * INTO v_invite
    FROM public.subsidiary_invites
    WHERE code = upper(trim(p_code))
    FOR UPDATE;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'invite code not found';
  END IF;
  IF v_invite.revoked_at IS NOT NULL THEN
    RAISE EXCEPTION 'invite code has been revoked';
  END IF;
  IF v_invite.claimed_at IS NOT NULL THEN
    RAISE EXCEPTION 'invite code already claimed';
  END IF;
  IF v_invite.inviter_id = v_uid THEN
    RAISE EXCEPTION 'cannot claim your own invite';
  END IF;

  v_expires := now() + (v_invite.duration_months || ' months')::interval;

  UPDATE public.subsidiary_invites
    SET claimed_at = now(),
        claimed_by = v_uid,
        expires_at = v_expires
    WHERE id = v_invite.id;

  -- Promote the caller's profile. Set the granted_tier + expiry,
  -- but DON'T clear an existing higher tier (someone who's already
  -- paying for vendor doesn't need a temporary collector grant).
  UPDATE public.profiles p
    SET subscription_tier        = v_invite.granted_tier,
        granted_tier_expires_at  = v_expires,
        granted_tier_source      = 'subsidiary_invite'
    WHERE p.id = v_uid
      AND public.tier_rank(coalesce(p.subscription_tier, 'free'))
          < public.tier_rank(v_invite.granted_tier);

  RETURN QUERY SELECT v_invite.granted_tier, v_expires;
END;
$$;
GRANT EXECUTE ON FUNCTION public.claim_subsidiary_invite(text) TO authenticated;


-- ── Tier rank helper ─────────────────────────────────────────
-- Needed by claim_subsidiary_invite (don't downgrade a paying
-- user when they claim a smaller invite). free < collector <
-- enthusiast < vendor < shop. NULL/unknown treats as free.
CREATE OR REPLACE FUNCTION public.tier_rank(p_tier text)
RETURNS int LANGUAGE sql IMMUTABLE AS $$
  SELECT CASE coalesce(lower(p_tier), 'free')
           WHEN 'free'       THEN 0
           WHEN 'collector'  THEN 1
           WHEN 'enthusiast' THEN 2
           WHEN 'vendor'     THEN 3
           WHEN 'shop'       THEN 4
           ELSE 0
         END;
$$;
GRANT EXECUTE ON FUNCTION public.tier_rank(text) TO anon, authenticated;


-- ── Expire grants ────────────────────────────────────────────
-- Drops users whose granted_tier_expires_at has elapsed back to
-- 'free'. Idempotent: only touches rows whose grant came from
-- subsidiary_invite (so manually-set tiers aren't clobbered).
-- Call from a daily Vercel cron or the existing GitHub Actions
-- nightly job.
CREATE OR REPLACE FUNCTION public.expire_subsidiary_grants()
RETURNS int LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE
  v_count int;
BEGIN
  UPDATE public.profiles
    SET subscription_tier       = 'free',
        granted_tier_expires_at = NULL,
        granted_tier_source     = NULL
    WHERE granted_tier_source     = 'subsidiary_invite'
      AND granted_tier_expires_at IS NOT NULL
      AND granted_tier_expires_at < now();
  GET DIAGNOSTICS v_count = ROW_COUNT;
  RETURN v_count;
END;
$$;
GRANT EXECUTE ON FUNCTION public.expire_subsidiary_grants() TO service_role;
